### PR TITLE
2.0

### PR DESCRIPTION
**Pull request by tagyoureit**
Here is the PR for all of the work that I've been doing.

### CODE REVIEW

**Comment by parnic** [comment]
I've been trying to read through this, and I've learned that I don't know TypeScript like at all 😅 .

Do you have an example of how the finder works with the new async stuff?

Once I got the example running, it looks like the line `console.log(' pool temp=' + status.currentTemp[0]);` should actually be `console.log(' pool temp=' + status.bodies[0].currentTemp);`. Otherwise, the get() methods seem be working (I commented out any setters so I don't disrupt my local config).

I'll go look up some "how to work with TypeScript" tutorials so I can learn how to use this. :)

**Comment by tagyoureit** [comment]
I have a couple calls today.  I've been hacking around with a different, local sample file.  I'll go through and fix/comment on the example.ts a little bit later.

**Comment by tagyoureit** [comment]
Try it again now.  I don't have my local unit with me, but think it should work.

**Comment by tagyoureit** [comment]
You get a chance to look at this?  Or need/want any help with it?

**Comment by parnic** [comment]
Sorry, busy week. Will try to get to this today

**Comment by parnic** [comment]
Alright, it's able to find my local unit, but then connects to it remotely instead of a direct network connection. I think I can figure out that part, so it's not a blocker for acceptance.

Is there a way to have this finder return units as soon as it finds them? I assume that would need an event-based implementation instead of an async/await one since it looks like the current method looks for 5 seconds and sends back everything it finds at once.

**Comment by tagyoureit** [comment]
Hi, where are we on this?  You get a chance to test?  Still have any issues?

**Comment by parnic** [comment]
Was waiting for a response to my last comment :)

**Comment by tagyoureit** [comment]
D'oh!  Are you on Discord?

**Comment by parnic** [comment]
Sure. Parnic#5314

**Comment by tagyoureit** [comment]
Invite sent

**Pull request merged**
