### PR TITLE
BugFix: gatewayName message.toString() conversion was stripping final character

### PR DESCRIPTION
**Pull request by mikemucc**
Found a small bug with gatewayName, I noticed it was stripping the final character.
Increased the range from 28 to 29 and it fixed the issue.

@parnic

### CODE REVIEW

**Comment by parnic** [comment]
Interesting, not sure how I never caught this. Thanks!

**Comment by mikemucc** [comment]
Well, I've now got a REST api wrapped around this, and I'm seeing my system name every time I hit the API, and after a while I noticed "I'm missing a character on this... Hmmm". Probably took me over a month to notice.

**Comment by schemers** [comment]
can you publish a 1.3.1 module with this fix? I'm messing around with Homebridge and was planning on using the discovered name to help compute a persistent id. thanks!

**Comment by mikemucc** [comment]
Agreed. I'm about to do a release of my Screenlogic API and Angular UI as well and would prefer to include 1.3.1 as the dependency.
@schemers You might be interested in this as well: https://github.com/mikemucc/screenlogic-api

**Comment by parnic** [comment]
Pushed.

**Pull request merged**
